---
abstract: 'Convert or render graphs (as ASCII, HTML, SVG or via Graphviz)'
author:
  - 'Tels <nospam-abuse@bloodgate.com>'
build_requires:
  Test::More: 0.62
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Graph::Easy
name: Graph-Easy
no_index:
  directory:
    - examples
    - bench
    - todos
    - inc
    - t
    - examples
recommends:
  Graph::Easy::As_svg: 0.23
requires:
  Scalar::Util: 1.13
  perl: 5.008002
version: 0.64
