--- #YAML:1.0
name: Graph-Easy
version: 0.18
version_from: lib/Graph/Easy.pm
license: gpl
distribution_type: module
generated_by: Graph-Easy version 0.18
installdirs: site
requires:
  Graph: 0.65
  Pod::Simple: 3.02
