abstract: Render graphs as ASCII, HTML, SVG or via Graphviz
author: Tels <nospam-abuse@bloodgate.com>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.63
license: gpl
name: Graph-Easy
no_index: 
  directory: 
    - examples
    - bench
    - todos
    - inc
    - t
recommends: 
  Graph::Easy::As_svg: 0.21
requires: 
  Scalar::Util: 1.13
  perl: 5.8.1
version: 0.48
