--- #YAML:1.0
name: Graph-Easy
version: 0.35
version_from: lib/Graph/Easy.pm
license: gpl
distribution_type: module
generated_by: Graph-Easy version 0.35
installdirs: site
requires:
  Heap: 0.71
  Scalar::Util: 1.13
