---
abstract: 'Convert or render graphs (as ASCII, HTML, SVG or via Graphviz)'
author:
  - unknown
build_requires:
  Test::More: '0.62'
configure_requires:
  Module::Build: '0.36'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
keywords:
  - generation
  - graph
  - graphviz
  - 'text generation'
  - text
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Graph-Easy
no_index:
  directory:
    - examples
    - bench
    - todos
recommends:
  Graph::Easy::As_svg: '0.23'
requires:
  Scalar::Util: '1.13'
  perl: v5.8.2
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  license: http://www.gnu.org/licenses/old-licenses/gpl-1.0.txt
  repository: https://bitbucket.org/shlomif/perl-graph-easy
version: '0.74'
