=pod

=head1 Graph::Easy manual - Overview

=head2 Introduction

=begin graph

 [ Source ] -Parser-> [ Internal objects ]
 -Layouter-> [ Layout ]

 [ Layout ] -output as-> [ ASCII ]
 [ Layout ] -output as-> [ HTML ]
 [ Layout ] -output as-> [ Graphviz ]
 [ Layout ] -output as-> [ SVG ]

=end graph

=head2 First steps

Paragraph one (1) with some text.

=begin graph-common

node { background: #ffdead; }

=end graph-common

Another paragraph lives here. A graph follows it:

=begin graph

  [ Text ] -Parser-> [ Internal format ]
  -Layouter-> [ Layout ]

  -Output-> [ HTML/ASCII/SVG/Graphviz etc ]

=end graph

Paragraph two (2) with some text.

Paragraph three (3) with some text.

Paragraph four (4) with some text. A graph follows:

=for graph [ A ] => [ B ]

Paragraph five (5) with some text. Another graph follows:

=for graph [ A ] -> [ C ]

=over 2

=item *

Some item.

=item *

Another item.

=back

Last paragraph of text.

=cut
