=pod

=head1 Graph::Easy manual

This manual was last updated on B<2005-05-30>.

=head2 Introduction

This manual aims to be a complete descriptions of the syntax of the
language that is used to describe graphs for the Graph::Easy project.

It features many examples, and most of them are shown both as the
source text and the resulting graph side by side like this:

=head2 Table of Contents

=begin graph

# Elan and Roy on Teamwork
# http://www.cafepress.com/orderofthestick.10272636?zoom=yes#zoom

[ Teamwork ] { background: yellow; title: Elan; }
-is the key to --> [ Victory ] { background: red; title: Roy; }

=end graph

##indextable##

=cut
